extends CanvasLayer

# AUTO-GENERATED by sdk/game_engine/provisioning/loading_screen.py.
# Do NOT edit by hand -- regenerated on every build from the canonical
# template. Per-game theming flows through res://assets/ui/theme.tres
# (ProgressBar/fill stylebox color), so Claude's creative control over
# the bar accent works without touching this file.
#
# Layout rules baked in (see .claude/skills/godot-loading-screen):
#   R1: wordmark uses explicit anchors symmetric around 0.5
#   R2: bottom band anchored to viewport bottom with NEGATIVE offset_top
#   R3: autoload owns PRELOAD_PATHS + _cache + _busy + calls
#       change_scene_to_packed (not _to_file)

# Filled in at engine provisioning time by walking the game's assets/ and
# scenes/. Ordered small/fast -> big/slow so the bar fills smoothly as
# the slower assets land at the end.
const PRELOAD_PATHS: PackedStringArray = [
	# -- Scenes --
	"res://scenes/game_world.tscn",
	"res://scenes/main.tscn",
	"res://scenes/ui/ending.tscn",
	# -- UI / textures / themes / fonts --
	"res://assets/fonts/noto_sans_kr.ttf",
	"res://assets/ui/app_icon.webp",
	"res://assets/ui/banner.webp",
	"res://assets/ui/btn_play.png",
	"res://assets/ui/btn_play.tres",
	"res://assets/ui/btn_quit.png",
	"res://assets/ui/btn_quit.tres",
	"res://assets/ui/cover.webp",
	"res://assets/ui/cover_sm.webp",
	"res://assets/ui/icon_lantern.png",
	"res://assets/ui/loading_bar_accent.tres",
	"res://assets/ui/loading_screen.png",
	"res://assets/ui/panel_rule.png",
	"res://assets/ui/panel_rule.tres",
	"res://assets/ui/theme.tres",
	"res://assets/ui/title_poster.webp",
	"res://assets/ui/title_poster_sm.webp",
	"res://assets/ui/wordmark_title.png",
	# -- World textures --
	"res://assets/sprites/characters/huldra_idle.png",
	"res://assets/sprites/characters/shadow_figure_idle.png",
	"res://assets/sprites/characters/traveler/traveler_hurt.png",
	"res://assets/sprites/characters/traveler/traveler_idle.png",
	"res://assets/sprites/characters/traveler/traveler_run.png",
	"res://assets/sprites/characters/traveler/traveler_walk.png",
	"res://assets/sprites/characters/traveler_back/traveler_back_idle.png",
	"res://assets/sprites/characters/traveler_back/traveler_back_walk.png",
	"res://assets/sprites/characters/traveler_cam/traveler_cam_hurt.png",
	"res://assets/sprites/characters/traveler_cam/traveler_cam_idle.png",
	"res://assets/sprites/characters/traveler_cam/traveler_cam_run.png",
	"res://assets/sprites/characters/traveler_cam/traveler_cam_walk.png",
	"res://assets/sprites/characters/traveler_front/traveler_front_idle.png",
	"res://assets/sprites/characters/traveler_front/traveler_front_walk.png",
	"res://assets/sprites/effects/camera_flash.png",
	"res://assets/sprites/items/anomaly_eyes.png",
	"res://assets/sprites/items/anomaly_stain.png",
	"res://assets/sprites/items/anomaly_writing.png",
	"res://assets/sprites/items/hotel_door.png",
	"res://assets/sprites/items/old_painting.png",
	"res://assets/sprites/items/rule_note.png",
	"res://assets/sprites/pickups/lantern.png",
	"res://assets/textures/backgrounds/corridor.png",
	"res://assets/textures/backgrounds/elevator_hall.png",
	"res://assets/textures/backgrounds/exterior.png",
	"res://assets/textures/backgrounds/guest_room.png",
	"res://assets/textures/backgrounds/lobby.png",
	"res://assets/textures/backgrounds/room_301.png",
	"res://assets/textures/backgrounds/room_302.png",
	"res://assets/textures/backgrounds/room_303.png",
	"res://assets/textures/backgrounds/room_304.png",
	"res://assets/textures/backgrounds/room_305.png",
	"res://assets/textures/backgrounds/room_306.png",
	"res://assets/textures/fx/light_radial.png",
	"res://assets/textures/fx/snow_dot.png",
	"res://assets/textures/fx/vignette.png",
	# -- Audio (music, SFX, ambient) --
	"res://assets/audio/ambient/ambient_abandoned_arctic_hotel_polar_night_hotel.mp3",
	"res://assets/audio/music/jingle_game_over_rule_violation_sting.mp3",
	"res://assets/audio/music/music_exploration_polaris_theme.mp3",
	"res://assets/audio/sfx/enemy/enemy_child_laugh.mp3",
	"res://assets/audio/sfx/enemy/enemy_heartbeat.mp3",
	"res://assets/audio/sfx/enemy/enemy_whistle_tune.mp3",
	"res://assets/audio/sfx/environment/environment_door_creak.mp3",
	"res://assets/audio/sfx/environment/environment_door_knock.mp3",
	"res://assets/audio/sfx/environment/environment_elevator_ding.mp3",
	"res://assets/audio/sfx/environment/environment_lantern_out.mp3",
	"res://assets/audio/sfx/player/player_camera_shutter.mp3",
	"res://assets/audio/sfx/player/player_footstep.mp3",
	"res://assets/audio/sfx/ui/ui_anomaly_fix.mp3",
	"res://assets/audio/sfx/ui/ui_camera_raise.mp3",
	"res://assets/audio/sfx/ui/ui_hover.mp3",
	"res://assets/audio/sfx/ui/ui_menu_click.mp3",
	"res://assets/audio/sfx/ui/ui_paper_rustle.mp3",
	"res://assets/audio/sfx/ui/ui_sleep_fade.mp3",
	"res://assets/audio/voice/nattmannen/voice_knock_307.mp3",
	"res://assets/audio/voice/nattmannen/voice_name_call.mp3",
]

# DEFAULT_ACCENT is the fallback bar-fill color when assets/ui/theme.tres
# doesn't ship a ProgressBar/fill stylebox. Picked to look reasonable on
# a black background.
const DEFAULT_ACCENT := Color(0.96, 0.70, 0.45, 1.0)
const DEFAULT_BG := Color(0.08, 0.08, 0.10, 0.85)

var _cache: Dictionary = {}
var _preloaded: bool = false
var _busy: bool = false
var _vfx_warmed: bool = false

var _root: Control
var _progress: ProgressBar
var _status: Label


func _ready() -> void:
	layer = 100
	process_mode = Node.PROCESS_MODE_ALWAYS
	visible = false
	_build_ui()


# Per-game accent resolution. Three lookups in priority order:
#
#  1. assets/ui/loading_bar_accent.tres  -- a StyleBoxFlat written by
#     Claude after generate_ui_kit, with bg_color matching the kit's
#     accent. This is the primary mechanism (see godot-loading-screen
#     skill).
#
#  2. assets/ui/theme.tres "ProgressBar/styles/fill" stylebox --
#     forward-compat for when/if generate_ui_kit ever synthesizes a
#     ProgressBar slot directly. Currently it doesn't, so this branch
#     is dormant but kept so a future upstream change Just Works.
#
#  3. DEFAULT_ACCENT -- neutral fallback when neither file is present
#     (e.g. a game that skipped the UI kit step).
func _resolve_accent() -> Color:
	if ResourceLoader.exists("res://assets/ui/loading_bar_accent.tres"):
		var sb := load("res://assets/ui/loading_bar_accent.tres") as StyleBoxFlat
		if sb:
			return sb.bg_color
	if ResourceLoader.exists("res://assets/ui/theme.tres"):
		var t := load("res://assets/ui/theme.tres") as Theme
		if t:
			var fill := t.get_stylebox("fill", "ProgressBar") as StyleBoxFlat
			if fill:
				return fill.bg_color
	return DEFAULT_ACCENT


func _build_ui() -> void:
	_root = Control.new()
	add_child(_root)
	_root.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	_root.mouse_filter = Control.MOUSE_FILTER_IGNORE

	# Solid black backdrop -- no grey flash even if the scenery image is
	# missing or still importing.
	var bg := ColorRect.new()
	bg.color = Color.BLACK
	_root.add_child(bg)
	bg.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)

	# Scenery image (loaded at runtime so we don't crash if missing).
	if ResourceLoader.exists("res://assets/ui/loading_screen.png"):
		var img := TextureRect.new()
		img.texture = load("res://assets/ui/loading_screen.png")
		img.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_COVERED
		img.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
		_root.add_child(img)
		img.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)

	# Subtle vignette so the wordmark and bar read against busy scenery.
	var vignette := ColorRect.new()
	vignette.color = Color(0, 0, 0, 0.30)
	_root.add_child(vignette)
	vignette.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)

	# Wordmark -- R1: explicit anchors, symmetric around 0.5. No
	# CenterContainer wrapper (would collapse on a CanvasLayer).
	if ResourceLoader.exists("res://assets/ui/wordmark_title.png"):
		var wm := TextureRect.new()
		wm.texture = load("res://assets/ui/wordmark_title.png")
		wm.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
		wm.expand_mode = TextureRect.EXPAND_FIT_WIDTH_PROPORTIONAL
		_root.add_child(wm)
		wm.anchor_left = 0.5
		wm.anchor_right = 0.5
		wm.anchor_top = 0.0
		wm.anchor_bottom = 0.0
		wm.offset_left = -450
		wm.offset_right = 450
		wm.offset_top = 80
		wm.offset_bottom = 380

	# Bottom band -- R2: anchor_top = anchor_bottom = 1.0, NEGATIVE
	# offset_top so the band sits INSIDE the viewport (not below).
	var band := Control.new()
	_root.add_child(band)
	band.anchor_left = 0.5
	band.anchor_right = 0.5
	band.anchor_top = 1.0
	band.anchor_bottom = 1.0
	band.offset_left = -360
	band.offset_right = 360
	band.offset_top = -160
	band.offset_bottom = -40

	var vbox := VBoxContainer.new()
	band.add_child(vbox)
	vbox.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	vbox.add_theme_constant_override("separation", 12)

	_status = Label.new()
	_status.text = "Loading..."
	_status.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	vbox.add_child(_status)

	# ProgressBar with explicit StyleBoxFlat overrides. The kit theme.tres
	# may not ship a ProgressBar style, in which case the default Godot
	# fill renders grey-on-grey and the bar looks stuck at 0%. Accent
	# comes from theme.tres "ProgressBar/fill" if available; else default.
	var accent := _resolve_accent()
	_progress = ProgressBar.new()
	_progress.min_value = 0.0
	_progress.max_value = 1.0
	_progress.show_percentage = false
	_progress.custom_minimum_size = Vector2(0, 22)
	var pb_bg := StyleBoxFlat.new()
	pb_bg.bg_color = DEFAULT_BG
	pb_bg.set_corner_radius_all(6)
	var pb_fill := StyleBoxFlat.new()
	pb_fill.bg_color = accent
	pb_fill.set_corner_radius_all(6)
	_progress.add_theme_stylebox_override("background", pb_bg)
	_progress.add_theme_stylebox_override("fill", pb_fill)
	vbox.add_child(_progress)


func _show() -> void:
	visible = true
	set_progress(0.0)


func _hide() -> void:
	visible = false


func set_progress(p: float) -> void:
	if _progress:
		_progress.value = clamp(p, 0.0, 1.0)
	if _status:
		_status.text = "Loading... %d%%" % int(p * 100.0)


# Heavy first-time warm-up. Honors a min_display floor so quick loads
# still show the screen long enough for the player to read.
func preload_and_change_scene(scene_path: String, min_display: float = 1.5) -> void:
	if _busy: return
	_busy = true
	_show()
	var t0 := Time.get_ticks_msec()
	await get_tree().process_frame
	await get_tree().process_frame  # double-frame render guarantee
	if not _preloaded:
		await _run_preload_sequence()  # fills 0% -> 92%
		_preloaded = true
	await _change_scene_to(scene_path)  # fills 92% -> 100%
	await _vfx_warmup()  # 3D-web: pre-compile VFX shaders while overlay covers the view
	var elapsed := float(Time.get_ticks_msec() - t0) / 1000.0
	if elapsed < min_display:
		await get_tree().create_timer(min_display - elapsed).timeout
	_hide()
	_busy = false


# Fast subsequent transition. Uses the cached PackedScene if it was
# warmed in the first preload pass; otherwise falls back to a fresh load.
func change_scene(scene_path: String, min_display: float = 0.6) -> void:
	if _busy: return
	_busy = true
	_show()
	var t0 := Time.get_ticks_msec()
	await get_tree().process_frame
	await get_tree().process_frame
	await _change_scene_to(scene_path)
	var elapsed := float(Time.get_ticks_msec() - t0) / 1000.0
	if elapsed < min_display:
		await get_tree().create_timer(min_display - elapsed).timeout
	_hide()
	_busy = false


# Synchronous load() per asset with a process_frame yield between each
# iteration. We deliberately do NOT use ResourceLoader.load_threaded_*
# here -- on single-threaded web (Godot 4's default web export, which
# is what most Tesana games target), there is no background thread, so
# load_threaded_get_status returns THREAD_LOAD_LOADED immediately on
# the first poll. The inner `while` loop then breaks BEFORE any
# `await get_tree().process_frame`, the whole 50+ iteration sequence
# runs in a single frame, and the bar appears to jump from 0% to 92%
# in one paint -- exactly the symptom that motivated threading in the
# first place.
#
# The simpler synchronous pattern below yields one frame per asset
# (independent of cache hits / missing files / load() runtime), so the
# bar repaints smoothly on EVERY web export configuration. For
# multi-threaded web with SharedArrayBuffer the per-asset frame yield
# is the only thing the bar cares about anyway -- you don't gain
# meaningful parallelism on the main thread that owns the renderer.
func _run_preload_sequence() -> void:
	var total := PRELOAD_PATHS.size()
	if total == 0:
		set_progress(0.92)
		return
	for i in total:
		var path := PRELOAD_PATHS[i]
		if _cache.has(path) or not ResourceLoader.exists(path):
			set_progress(float(i + 1) / float(total) * 0.92)
			await get_tree().process_frame
			continue
		var res := load(path)
		if res:
			_cache[path] = res
		else:
			push_warning("LoadingScreen preload failed: " + path)
		# Reserve the last 8% for the actual scene swap.
		set_progress(float(i + 1) / float(total) * 0.92)
		await get_tree().process_frame


func _change_scene_to(scene_path: String) -> void:
	var packed := _cache.get(scene_path) as PackedScene
	if packed:
		get_tree().change_scene_to_packed(packed)
	else:
		get_tree().change_scene_to_file(scene_path)
	set_progress(1.0)
	await get_tree().process_frame
	await get_tree().process_frame


# 3D-web VFX shader pre-compile.
#
# Godot compiles a material/shader variant the first time the renderer DRAWS
# it -- NOT when the resource is load()ed. The VFX root scenes are already
# warm in _cache (the asset walker lists every assets/3d_vfx/.../effects/*.tscn
# in PRELOAD_PATHS), but their shaders are still uncompiled. So the FIRST time
# an effect spawns in gameplay the main thread stalls ~150-300ms on
# single-threaded web while variants compile -- the "first explosion freezes
# the game" stutter.
#
# Fix: instance each VFX root ONCE, in front of the active camera so the
# renderer actually draws it (off-screen would not trigger compilation), let
# it render two frames, then free it. The full-screen loading overlay (this
# CanvasLayer, layer=100) hides the flash; the 3D pass still renders
# underneath, so the variants compile. Runs once, on the heavy first load,
# web + 3D only. Source of truth is PRELOAD_PATHS filtered to 3d_vfx effect
# roots -- no separate manifest needed.
func _vfx_warmup() -> void:
	if _vfx_warmed:
		return
	_vfx_warmed = true
	if not OS.has_feature("web"):
		return  # the first-draw stutter only manifests on single-threaded web
	var scene := get_tree().current_scene
	var cam := get_viewport().get_camera_3d()
	if scene == null or cam == null:
		return  # 2D game / no active 3D camera -> nothing to warm
	var vfx_paths: Array[String] = []
	for p in PRELOAD_PATHS:
		if p.ends_with(".tscn") and ("/3d_vfx/" in p) and ("/effects/" in p):
			vfx_paths.append(p)
	if vfx_paths.is_empty():
		return
	_status.text = "Preparing effects..."
	# Invisible holder in the current scene so effects compile against the real
	# light / fog / tonemap environment they will actually be used in.
	var holder := Node3D.new()
	scene.add_child(holder)
	var spawn_at := cam.global_position - cam.global_transform.basis.z * 3.0
	for path in vfx_paths:
		var ps := _cache.get(path) as PackedScene
		if ps == null and ResourceLoader.exists(path):
			ps = load(path) as PackedScene
		if ps == null:
			continue
		var inst: Node = ps.instantiate()
		# Same guards use_3d_vfx bakes in -- without them an effect with no
		# AnimationPlayer recurses to a stack overflow on add_child, and
		# proximity_fade renders invisible in GL Compatibility.
		if "autoplay" in inst:
			inst.set("autoplay", false)
		if "proximity_fade" in inst:
			inst.set("proximity_fade", false)
		holder.add_child(inst)
		if inst is Node3D:
			inst.global_position = spawn_at  # in frustum -> drawn -> shader compiled
		if inst.has_node("AnimationPlayer") and inst.has_method("play"):
			inst.call("play")
		await get_tree().process_frame
		await get_tree().process_frame
		if is_instance_valid(inst):
			inst.queue_free()
	if is_instance_valid(holder):
		holder.queue_free()
